config/routes.rb
Rails.application.routes.draw do
  # resources :films
  resources :posts
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/articles", to: "articles#index"
  # Defines the root path route ("/")
  root "articles#index"
  resources :films do
    collection do
      get :omdb_search
      post :omdb_import
    end

    resources :comments, only: %i[create edit update destroy]
  end

  resource :profile, only: %i[edit update], controller: :profiles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  has_many :comments, as: :commentable, dependent: :destroy

  validates :body, presence: true, length: { minimum: 4, maximum: 500 }
end

app/models/film.rb
class Film < ApplicationRecord
  GENRES = %w[action comedy drama horror romance thriller sci-fi fantasy animation documentary musical western].freeze

  has_many :comments, as: :commentable, dependent: :destroy

  # validates
  validates :name, :year_of_creation, presence: true
  validates :description, length: { minimum: 4 }
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy

  has_one_attached :avatar do |attachable|
    attachable.variant :tiny, resize_to_limit: [50, 50]
  end

  def full_name
    return email if first_name.blank? && last_name.blank?

    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  protect_from_forgery prepend: true
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_film, only: :create
  before_action :find_and_authorize_comment, except: :create

  def create
    @comment = Comment.new(comment_params.merge!(user: current_user))

    if @comment.save
      redirect_to film_path(@film)
    end
  end

  def edit
    authorize @comment
  end

  def update
    @comment.assign_attributes(comment_params)

    if @comment.save
      redirect_to @comment.commentable
    else
      flash[:error] = @comment.errors.full_messages.join(", ")
      p :error
      render :edit
    end
  end

  def destroy
    authorize @comment

    @comment.destroy!
  end

  private

  def find_film
    @film = Film.find(params[:film_id])
  end

  def find_and_authorize_comment
    @comment = Comment.find(params[:id])
    authorize @comment
  end

  def comment_params
    # params.require(:comment).permit(:body)
    params.require(:comment).permit(:body, :commentable_id, :commentable_type)
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: %i[ show edit update destroy ]

  # GET /films or /films.json
  def index
    @films = Film.all
  end

  # GET /films/1 or /films/1.json
  def show
    @omdb = OmdbService.new
    @omdb_film = @omdb.find_by_title(@film.name)
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films or /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to film_url(@film), notice: "Film was successfully created." }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1 or /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to film_url(@film), notice: "Film was successfully updated." }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1 or /films/1.json
  def destroy
    @film.destroy!

    respond_to do |format|
      format.html { redirect_to films_url, notice: "Film was successfully destroyed." }
      format.json { head :no_content }
    end
  end

# omdb
  def omdb_search
    if params[:search_query].present?
      @omdb = OmdbService.new

      # @search_results = @omdb.search(params[:search_query])['Search']
      res = @omdb.search(params[:search_query])
      @search_results = res['Search']
    end
  end

  def omdb_import
    @omdb = OmdbService.new

    @omdb_film = @omdb.find_by_id(params[:omdb_id])

    @film = Film.new(
      name: @omdb_film['Title'],
      cover_image_url: @omdb_film['Poster'],
      year_of_creation: @omdb_film['Year'],
      description: @omdb_film['Plot'],
      length: @omdb_film['Runtime'],
      director: @omdb_film['Director'],
      genres: @omdb_film['Genre'].split(', ')
    )
    if @film.save
      redirect_to @film
    else
      flash[:error] = @film.errors.full_messages.join(", ")
      render :omdb_search
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def film_params
      params.require(:film)
      .permit(:name, :description, :year_of_creation, :director, :length, :cover_image_url, genres: [])
    end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :description, :release_date, :director, :length)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def edit
  end

  def update
    if current_user.update(profile_params)
      flash[:notice] = 'Profile updated'
      redirect_to root_path
    else
      flash[:alert] = current_user.errors.full_messages.join(", ")
    end
  end

  private

  def profile_params
    params.require(:user).permit(:first_name, :last_name, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/articles/index.html.erb
<h1></h1>

app/views/comments/_form.html.erb
<h2>Create comment</h2>
<% if comment_to.is_a?(Film) %>
  <% film = comment_to %>
  <h4>Create</h4>
<% elsif comment_to.is_a?(Comment) %>
  <% film = comment_to.commentable %>
  <h5>Reply</h5>
<% end %>
<%= form_for :comment, url: film_comments_path(film) do | form |%>
    <%= form.hidden_field :commentable_type, value: comment_to.class.name %>
    <%= form.hidden_field :commentable_id, value: comment_to.id %>
    <%= render 'comments/form_field', form: form %>

    <%= form.submit %>
<% end %>

app/views/comments/_form_field.html.erb
<%= form.text_field :body%>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@comment)%>

app/views/comments/edit.html.erb
<%= turbo_frame_tag dom_id(@comment) do %>
    <h2>Edit comment <%= @comment.id%> (by <%= @comment.user.email%>)</h2>
    <div>
    <%= form_for @comment, url: film_comment_path(@comment, film_id: @comment.commentable_id) do | form |%>
        <%= render 'comments/form_field', form: form%>
        
        <%= form.submit %>

    <% end %>
    </div>
<% end %>

app/views/films/_film.html.erb
<div id="<%= dom_id film %>" class="card">
  <% if film.cover_image_url %>
    <div class="card-image">
      <%= image_tag(film.cover_image_url) %>
    </div>
  <% end %>
  <div class="card-content">
    <p class="card-title">
      <strong>Name:</strong>
      <%= film.name %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= film.description %>
    </p>

    <p>
      <strong>Year of creation:</strong>
      <%= film.year_of_creation %>
    </p>

    <p>
      <strong>Director:</strong>
      <%= film.director %>
    </p>

    <p>
      <strong>Length:</strong>
      <%= film.length %>
    </p>

    <p>
      <strong>Genres:</strong>
      <%= film.genres.filter_map { |g| g.titleize if g.present? }.join(', ') %>
    </p>
  </div>
</div>

<div id="<%= dom_id film %>">

app/views/films/_form.html.erb
<div class="centered-container">
  <%= form_with(model: film, class: "form") do |form| %>
    <% if film.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

        <ul>
          <% film.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description %>
    </div>

    <div>
      <%= form.label :year_of_creation, style: "display: block" %>
      <%= form.number_field :year_of_creation %>
    </div>

    <div>
      <%= form.label :director, style: "display: block" %>
      <%= form.text_field :director %>
    </div>

    <div>
      <%= form.label :length, style: "display: block" %>
      <%= form.number_field :length %>
    </div>

    <div>
      <%= form.label :genres, style: 'display: block'%>
      <%= form.select :genres, Film::GENRES, multiple: true%>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/films/edit.html.erb
<h1>Editing film</h1>

<%= render "form", film: @film %>

<br>

<div>
  <%= link_to "Show this film", @film %> |
  <%= link_to "Back to films", films_path %>
</div>

app/views/films/index.html.erb
<p class="success"><%= notice %></p>

<h1>Films</h1>

<ul class="films" id="films">
  <% @films.each do |film| %>
    <li class="film">
      <% if film.cover_image_url %>
        <%= image_tag(film.cover_image_url) %>
      <% end %>
      <h3 class="name">
        <%= film.name %>
      </h3>
      <button class="btn show">
        <%= link_to "Show this film", film %>
      </button>
    </li>
  <% end %>
</ul>

<%= link_to "New film", new_film_path, class: "btn" %>

app/views/films/new.html.erb
<h1>New film</h1>

<%= render "form", film: @film %>

<br>

<div>
  <%= link_to "Back to films", films_path %>
</div>

app/views/films/omdb_search.html.erb
<h1>Omdb search</h1>
<%= form_tag omdb_search_films_path, method: :get do %>
  <div style='margin-bottom: 10px;'>
    <%= label_tag :search_query %>
    <%= text_field_tag :search_query, params[:search_query] %>
  </div>

  <%= submit_tag 'Search' %>
<% end %>
<% if @search_results.present? %>
  <table>
    <thead>
    <th>Name</th>
    <th>Year</th>
    <th>Image</th>
    <th>Actions</th>
    </thead>
    <tbody>
    <% @search_results.each do |film| %>
      <tr>
        <td><%= film['Title'] %></td>
        <td><%= film['Year'] %></td>
        <td><%= image_tag(film['Poster']) %></td>
        <td>
          <%= form_tag omdb_import_films_path(omdb_id: film['imdbID']), method: :post do %>
            <%= submit_tag 'Import' %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/films/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @film %>

<div>
  <%= link_to "Edit this film", edit_film_path(@film) %> |
  <%= link_to "Back to films", films_path %>

  <%= button_to "Destroy this film", @film, method: :delete %>

  <% @film.comments.includes(:user).each do | comment |%>
    <%= turbo_frame_tag(dom_id(comment)) do %>
      <p><%= comment.body %> (by <%= comment.user.email %>) 
        <% if policy(comment).edit?%>
          <%= link_to('edit', edit_film_comment_path(comment, film_id: comment.commentable.id)) %>
        <% end %>

        <% if policy(comment).destroy?%>
          <%= link_to('destroy', film_comment_path(comment, film_id: comment.commentable.id), method: :delete, data:  { turbo_method: :delete}) %>
        <% end %>
        <div>
          <% comment.comments.includes(:user).each do |sub_comment| %>
            <%= sub_comment.body %> (by <%= sub_comment.user.email %>)
            <br/>
          <% end %>
          <%= render partial: 'comments/form', locals: { comment_to: comment } %>
        </div>
      </p>
    <% end %>
  <% end %>
  <%= render partial: 'comments/form', locals: {comment_to: @film}%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
     <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header'%>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "main", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class='container'>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :release_date, style: "display: block" %>
    <%= form.date_field :release_date %>
  </div>

  <div>
    <%= form.label :director, style: "display: block" %>
    <%= form.text_field :director %>
  </div>

  <div>
    <%= form.label :length, style: "display: block" %>
    <%= form.number_field :length %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Name:</strong>
    <%= post.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= post.description %>
  </p>

  <p>
    <strong>Release date:</strong>
    <%= post.release_date %>
  </p>

  <p>
    <strong>Director:</strong>
    <%= post.director %>
  </p>

  <p>
    <strong>Length:</strong>
    <%= post.length %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/profiles/edit.html.erb
<h1><%= current_user.full_name %></h1>
<% if current_user.avatar.attached? %>
  <%= image_tag(current_user.avatar) %>
<% end %>

<article>
  <%= form_for(current_user, url: profile_path(current_user), method: :put) do |f| %>
    <div>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div>
      <%= f.file_field :avatar %>
    </div>
    <%= f.submit %>
  <% end %>
</article>

app/views/shared/_header.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <%= stylesheet_link_tag "main", "data-turbo-track": "reload" %>
    <style>
        .top-right {
            position: absolute;
            top: 10px;
            right: 10px;
        }
        .header .container  .btn {
            width: 100%;
            max-width: 150px;
            display: block;
        }
        .header .container {
            display: flex;
            align-items: center;
            justify-content: space-between;
        }
        .header .container .links {
            display: flex;
            gap: 20px;
        }
        .header .container .links .link a {
            color: #000;
        }
        .header .container .class {
            display: block;
            margin-right: 100px;
        }
    </style>
</head>
<body>
    <header class='header'>
        <div class='container'>
            <h1>Project</h1>
            <ul class="links">
                <li class="link">
                    <a href='/'>Home</a>
                </li>
                <li class="link">
                    <a href='/films'>Films</a>
                </li>
                <li class="link">
                    <%= link_to 'Search', omdb_search_films_path %>
                </li>
            </ul>
            <div class="class">
                <%= image_tag(current_user.avatar.variant(:tiny)) if current_user.avatar.attached? %>
                <%= link_to(current_user.full_name, edit_profile_url) %>    
            <div/>
            <div>
                <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger top-right" %>
            <div/>
        </div>
    </header>
</body>
</html>